-- JOIN의 종류
-- INNER JOIN A n B <- 교집합
-- LEFT RIGHT OUTER JOIN <- (A n B) U (A - B)
-- FULL JOIN (사용빈도 낮음) 사용하면 욕먹기 딱 좋음

-- [INNER or OUTER or FULL] [JOIN] ON key = key, 조건 = 조건
SELECT E.*
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                 LEFT OUTER JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
                 LEFT OUTER JOIN COUNTRIES C ON C.COUNTRY_ID = L.COUNTRY_ID
                 LEFT OUTER JOIN REGIONS R ON R.REGION_ID = C.REGION_ID;
-- FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.EMPLOYEE_ID = D.DEPARTMENT_NAME; JOIN이 정확히 안되어서
-- 결과 출력할 수 없다