-- 시퀀스 : 만들기, 쓰기
-- CREATE TABLE [이름]
-- 특정 값만큼 증가하는 구분자용 1부터 시작해서 n씩 증가. NEXTVAL, CURRVAL
-- CREATE SEQUENCE [이름] INCREMENT BY 증가값[NUMBER, INT];
-- CURRVAL : 현재 시퀀스의 값
-- NEXTVAL : 현재 시퀀스값 + 증가값 ( 값변경이 있다 )
-- CREATE <-> DROP

DROP SEQUENCE SEQ_AND_BOARD;
CREATE SEQUENCE SEQ_TEST INCREMENT BY 1;
CREATE SEQUENCE SEQ_TEST2 INCREMENT BY 5;

SELECT SEQ_TEST2.NEXTVAL FROM DUAL;
CREATE SEQUENCE SEQ_SSS INCREMENT BY 1;

CREATE SEQUENCE SEQ_AND_BOARD INCREMENT BY 1;
SELECT SEQ_AND_BOARD.CURRVAL FROM DUAL;

INSERT INTO AND_BOARD (BOARD_CATEGORY, BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DATE, CREATE_BY)
               VALUES ('B', SEQ_AND_BOARD.NEXTVAL, '제목', '내용', SYSDATE, 'dev');
COMMIT;
               
SELECT * FROM AND_BOARD;
ROLLBACK;
