DESC MEMBER;

INSERT INTO MEMBER(MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_CALL, MEMBER_AGE) VALUES ('AAA', '1234', '홍길동', '01012345678', 20);

UPDATE MEMBER SET MEMBER_ID = 'QPQP' , MEMBER_CALL = '00000000' WHERE MEMBER_NAME = '가나다';

COMMIT;

SELECT NVL(MAX(TEXT_NUMBER),0)+1 FROM BOARD2;

INSERT INTO BOARD2 (TEXT_NUMBER, TITLE, CONTENTS, MEMBER_ID, WRITE_DATE) SELECT (MAX(TEXT_NUMBER))+1 ,'asdf', 'asdfd', 'adsf', SYSDATE FROM BOARD2 ;



